"""Schedule a one-shot `harness resume` via macOS launchd.

Used when a subscription runner reports a usage cap. The orchestrator
catches the rate-limit error, asks this module to schedule a resume
shortly after the reset time, and exits cleanly. When the time hits,
launchd fires our wrapper script which unloads the agent first (so the
calendar interval can't re-fire next month) and then runs `harness
resume` against the project directory.

Linux/non-darwin returns False from `is_supported()` — callers should
fall back to printing a manual-resume hint.
"""

import os
import platform
import shutil
import stat
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional


def is_supported() -> bool:
    return platform.system() == "Darwin" and shutil.which("launchctl") is not None


def _label(project_id: str) -> str:
    return f"com.harness.resume.{project_id}"


def _plist_path(project_id: str) -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{_label(project_id)}.plist"


def _wrapper_path(project_dir: Path) -> Path:
    return project_dir / ".auto_resume.sh"


def _log_path(project_dir: Path) -> Path:
    return project_dir / "auto_resume.log"


def cancel(project_id: str) -> None:
    """Best-effort: unload + remove any prior schedule for this project."""
    plist = _plist_path(project_id)
    if not plist.exists():
        return
    label = _label(project_id)
    uid = os.getuid()
    subprocess.run(
        ["launchctl", "bootout", f"gui/{uid}/{label}"],
        capture_output=True,
    )
    subprocess.run(
        ["launchctl", "unload", str(plist)],
        capture_output=True,
    )
    try:
        plist.unlink()
    except FileNotFoundError:
        pass


def schedule(
    project_dir: Path,
    project_id: str,
    fire_at_utc: datetime,
    harness_binary: Optional[str] = None,
    buffer_seconds: int = 300,
) -> dict:
    """Schedule one `harness resume` invocation slightly after fire_at_utc.

    Returns a dict with paths and the local fire time, suitable for the
    orchestrator to display.
    """
    if not is_supported():
        raise RuntimeError("launchd auto-resume only supported on macOS.")

    project_dir = project_dir.resolve()
    harness_binary = harness_binary or shutil.which("harness") or "harness"

    fire_local = (fire_at_utc + timedelta(seconds=buffer_seconds)).astimezone()
    plist = _plist_path(project_id)
    wrapper = _wrapper_path(project_dir)
    log = _log_path(project_dir)
    label = _label(project_id)

    # Wipe any previous schedule for this project before writing a new one.
    cancel(project_id)

    plist.parent.mkdir(parents=True, exist_ok=True)
    log.touch(exist_ok=True)

    wrapper.write_text(_wrapper_script(
        project_dir=project_dir,
        harness_binary=harness_binary,
        plist_path=plist,
        label=label,
        log_path=log,
    ))
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    plist.write_text(_plist_xml(
        label=label,
        wrapper_path=wrapper,
        log_path=log,
        fire_local=fire_local,
    ))

    uid = os.getuid()
    bootstrap = subprocess.run(
        ["launchctl", "bootstrap", f"gui/{uid}", str(plist)],
        capture_output=True,
        text=True,
    )
    if bootstrap.returncode != 0:
        # Older macOS — fall back to legacy load.
        load = subprocess.run(
            ["launchctl", "load", str(plist)],
            capture_output=True,
            text=True,
        )
        if load.returncode != 0:
            raise RuntimeError(
                f"launchctl could not load {plist}: "
                f"{load.stderr or bootstrap.stderr}"
            )

    return {
        "label": label,
        "plist": plist,
        "wrapper": wrapper,
        "log": log,
        "fire_local": fire_local,
        "fire_utc": fire_at_utc + timedelta(seconds=buffer_seconds),
    }


def _wrapper_script(
    project_dir: Path,
    harness_binary: str,
    plist_path: Path,
    label: str,
    log_path: Path,
) -> str:
    return f"""#!/bin/bash
# Auto-generated by harness — do not edit by hand.
# Fires once when the subscription rate limit is expected to have reset.

set -u

PROJECT_DIR="{project_dir}"
HARNESS="{harness_binary}"
PLIST="{plist_path}"
LABEL="{label}"
LOG="{log_path}"
UID_NUM="$(id -u)"

echo "" >> "$LOG"
echo "[$(date '+%Y-%m-%d %H:%M:%S %z')] auto-resume firing" >> "$LOG"

# Unload BEFORE the run so the calendar entry can't fire again next month
# even if the resume itself takes a long time.
launchctl bootout "gui/${{UID_NUM}}/${{LABEL}}" 2>/dev/null
launchctl unload "$PLIST" 2>/dev/null

cd "$PROJECT_DIR"
"$HARNESS" resume "$PROJECT_DIR" >> "$LOG" 2>&1
EXIT=$?
echo "[$(date '+%Y-%m-%d %H:%M:%S %z')] auto-resume exited $EXIT" >> "$LOG"
exit $EXIT
"""


def _plist_xml(label: str, wrapper_path: Path, log_path: Path, fire_local: datetime) -> str:
    # StartCalendarInterval has no Year — daemon fires next matching slot.
    # The wrapper unloads us as its first action, so re-fires next month
    # cannot happen.
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{wrapper_path}</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Month</key>
        <integer>{fire_local.month}</integer>
        <key>Day</key>
        <integer>{fire_local.day}</integer>
        <key>Hour</key>
        <integer>{fire_local.hour}</integer>
        <key>Minute</key>
        <integer>{fire_local.minute}</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>{log_path}</string>
    <key>StandardErrorPath</key>
    <string>{log_path}</string>
    <key>RunAtLoad</key>
    <false/>
</dict>
</plist>
"""
